import { VEHICLE_BRAND_OPTIONS } from "@/lib/vehicle-brands";

export const VEHICLE_MODELS_BY_BRAND: Partial<Record<(typeof VEHICLE_BRAND_OPTIONS)[number], string[]>> = {
  Abarth: ["500", "595", "695", "Punto", "Grande Punto", "124 Spider"],
  "Alfa Romeo": [
    "Giulia",
    "Giulietta",
    "Stelvio",
    "Tonale",
    "MiTo",
    "147",
    "156",
    "159",
    "Brera",
    "GT",
    "Spider",
    "4C",
    "33",
    "75",
    "145",
    "146",
    "166",
    "GTV",
  ],
  Alpine: ["A110", "A310", "GTA", "A290"],
  "Aston Martin": ["DB11", "DB12", "DBS", "Vantage", "Vanquish", "Rapide", "DBX"],
  Audi: [
    "A1",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q7",
    "Q8",
    "TT",
    "R8",
    "e-tron GT",
    "RS3",
    "RS4",
    "RS6",
    "S3",
    "S4",
  ],
  Bentley: ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne", "Arnage"],
  BMW: [
    "Serie 1",
    "Serie 2",
    "Serie 3",
    "Serie 4",
    "Serie 5",
    "Serie 6",
    "Serie 7",
    "Serie 8",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z3",
    "Z4",
    "i3",
    "i4",
    "iX",
    "M2",
    "M3",
    "M4",
    "M5",
  ],
  BYD: ["Atto 3", "Dolphin", "Seal", "Han", "Tang", "Song Plus"],
  Cadillac: ["Escalade", "CTS", "XT4", "XT5", "XT6", "CT5", "CT6"],
  Chevrolet: ["Aveo", "Spark", "Cruze", "Captiva", "Orlando", "Matiz", "Camaro", "Corvette"],
  Chrysler: ["300C", "Voyager", "Grand Voyager", "PT Cruiser", "Crossfire"],
  Citroën: [
    "C1",
    "C2",
    "C3",
    "C3 Aircross",
    "C4",
    "C4 Cactus",
    "C4 Picasso",
    "C5",
    "C5 Aircross",
    "C5 X",
    "C6",
    "C8",
    "Berlingo",
    "DS3",
    "Xsara",
    "Saxo",
    "Jumpy",
    "ë-C4",
  ],
  Cupra: ["Formentor", "Leon", "Ateca", "Born", "Tavascan"],
  Dacia: ["Sandero", "Duster", "Logan", "Lodgy", "Dokker", "Jogger", "Spring"],
  Daihatsu: ["Sirion", "Terios", "Cuore", "YRV", "Materia"],
  DFSK: ["Glory 580", "K01", "Fengon"],
  Dodge: ["Charger", "Challenger", "Nitro", "Journey", "Caliber", "Durango", "Ram"],
  "DR Automobiles": ["DR1", "DR3", "DR4", "DR5", "DR5.0", "DR6", "DR7", "F35"],
  "DS Automobiles": ["DS3", "DS4", "DS5", "DS7 Crossback", "DS9"],
  Ferrari: ["296", "812", "F8", "Roma", "Portofino", "SF90", "Purosangue", "California", "458", "488", "599", "612", "F430", "Testarossa"],
  Fiat: [
    "Panda",
    "500",
    "500L",
    "500X",
    "Punto",
    "Grande Punto",
    "Tipo",
    "Bravo",
    "Stilo",
    "Doblo",
    "Ducato",
    "Ulysse",
    "Multipla",
    "Idea",
    "Croma",
    "Marea",
    "Sedici",
    "Freemont",
    "Qubo",
    "600",
    "Fullback",
    "Palio",
    "Uno",
    "Ritmo",
  ],
  Ford: [
    "Fiesta",
    "Focus",
    "Mondeo",
    "Ka",
    "Puma",
    "Kuga",
    "EcoSport",
    "Edge",
    "S-Max",
    "Galaxy",
    "C-Max",
    "B-Max",
    "Mustang",
    "Explorer",
    "Transit",
    "Tourneo",
    "Ranger",
  ],
  Genesis: ["G70", "G80", "G90", "GV70", "GV80"],
  Honda: ["Civic", "Jazz", "CR-V", "HR-V", "Accord", "City", "Insight", "Legend", "S2000", "e"],
  Hyundai: [
    "i10",
    "i20",
    "i30",
    "i40",
    "Tucson",
    "Santa Fe",
    "Kona",
    "Bayon",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 6",
    "Elantra",
    "Getz",
    "Matrix",
    "Accent",
  ],
  Ineos: ["Grenadier"],
  Infiniti: ["Q30", "Q50", "Q60", "QX30", "QX50", "QX70"],
  Isuzu: ["D-Max", "Trooper", "Rodeo"],
  Iveco: ["Daily"],
  Jaguar: ["XE", "XF", "XJ", "F-Type", "F-Pace", "E-Pace", "I-Pace", "X-Type", "S-Type"],
  Jeep: ["Renegade", "Compass", "Wrangler", "Grand Cherokee", "Cherokee", "Avenger", "Patriot"],
  Kia: ["Picanto", "Rio", "Ceed", "Sportage", "Sorento", "Stonic", "Niro", "Soul", "Optima", "Venga", "EV6", "Carens"],
  Lada: ["Niva", "Samara", "4x4"],
  Lamborghini: ["Huracán", "Aventador", "Urus", "Gallardo", "Murciélago", "Diablo"],
  Lancia: ["Ypsilon", "Delta", "Musa", "Thesis", "Lybra", "Kappa", "Dedra", "Thema"],
  "Land Rover": [
    "Range Rover",
    "Range Rover Sport",
    "Range Rover Evoque",
    "Range Rover Velar",
    "Discovery",
    "Discovery Sport",
    "Defender",
    "Freelander",
  ],
  Lexus: ["CT", "IS", "ES", "GS", "LS", "NX", "RX", "UX", "RC", "LC"],
  Lotus: ["Elise", "Exige", "Evora", "Emira", "Eletre"],
  Maserati: ["Ghibli", "Quattroporte", "Levante", "GranTurismo", "GranCabrio", "MC20", "Grecale"],
  Maybach: ["57", "62", "Classe S Maybach"],
  Mazda: ["2", "3", "6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "MX-30"],
  McLaren: ["570S", "720S", "650S", "GT", "Artura", "12C"],
  "Mercedes-Benz": [
    "Classe A",
    "Classe B",
    "Classe C",
    "Classe E",
    "Classe S",
    "CLA",
    "CLS",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "Classe G",
    "SLK",
    "SL",
    "Vito",
    "Sprinter",
    "EQA",
    "EQB",
    "EQC",
    "EQE",
    "EQS",
  ],
  MG: ["ZS", "HS", "MG3", "MG4", "MG5", "Marvel R"],
  Mini: ["Cooper", "One", "Countryman", "Clubman", "Paceman", "Cabrio"],
  Mitsubishi: ["Colt", "Space Star", "ASX", "Outlander", "Eclipse Cross", "Pajero", "L200"],
  Nissan: ["Micra", "Note", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "Navara", "Pathfinder", "370Z", "GT-R"],
  Opel: ["Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland", "Zafira", "Meriva", "Adam", "Karl", "Antara", "Vectra"],
  Peugeot: ["108", "208", "308", "2008", "3008", "5008", "508", "Partner", "Rifter", "107", "206", "207", "306", "307", "407", "607"],
  Polestar: ["1", "2", "3", "4"],
  Porsche: ["911", "718", "Cayenne", "Macan", "Panamera", "Taycan", "Boxster", "Cayman"],
  Renault: ["Clio", "Captur", "Megane", "Scenic", "Twingo", "Kadjar", "Koleos", "Talisman", "Zoe", "Espace", "Laguna", "Kangoo", "Modus", "Austral"],
  "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Spectre"],
  Rover: ["25", "45", "75", "200", "400", "600", "800"],
  Saab: ["9-3", "9-5", "900", "9000"],
  Seat: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Alhambra", "Toledo", "Altea", "Exeo"],
  Skoda: ["Fabia", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Scala", "Enyaq", "Rapid", "Yeti", "Citigo"],
  Smart: ["ForTwo", "ForFour", "Roadster"],
  SsangYong: ["Korando", "Tivoli", "Rexton", "Actyon", "Musso"],
  Subaru: ["Impreza", "Legacy", "Forester", "Outback", "XV", "BRZ", "Levorg"],
  Suzuki: ["Swift", "Vitara", "SX4", "Jimny", "Ignis", "S-Cross", "Baleno", "Celerio", "Across"],
  Tesla: ["Model S", "Model 3", "Model X", "Model Y"],
  Toyota: [
    "Yaris",
    "Corolla",
    "Auris",
    "Avensis",
    "RAV4",
    "C-HR",
    "Aygo",
    "Camry",
    "Prius",
    "Land Cruiser",
    "Hilux",
    "Supra",
    "GR86",
    "bZ4X",
    "Highlander",
  ],
  Volkswagen: [
    "Polo",
    "Golf",
    "Passat",
    "Tiguan",
    "Touareg",
    "T-Roc",
    "T-Cross",
    "Arteon",
    "Up",
    "Jetta",
    "Sharan",
    "Touran",
    "Scirocco",
    "Beetle",
    "ID.3",
    "ID.4",
    "ID.5",
    "Caddy",
    "Multivan",
  ],
  Volvo: ["V40", "V60", "V70", "V90", "S60", "S80", "S90", "XC40", "XC60", "XC90", "C30", "C40"],
};

export function getVehicleModelsForBrand(brand: string): string[] {
  return VEHICLE_MODELS_BY_BRAND[brand as (typeof VEHICLE_BRAND_OPTIONS)[number]] ?? [];
}
