export const VEHICLE_EQUIPMENT_OPTIONS = [
  "360° camera",
  "ABS",
  "Abilitata per E10",
  "Adaptive Cruise Control",
  "Adatto a portatori di handicap",
  "Airbag conducente",
  "Airbag laterali",
  "Airbag passeggero",
  "Airbag posteriore",
  "Airbag testa",
  "Alzacristalli elettrici",
  "Android Auto",
  "Antifurto",
  "Apple CarPlay",
  "Assistente abbaglianti",
  "Autoradio",
  "Autoradio digitale",
  "Blind spot monitor",
  "Bluetooth",
  "Bracciolo",
  "Carica per smartphone a induzione",
  "CD",
  "Cerchi in lega",
  "Cerchioni in acciaio",
  "Certificato della batteria",
  "Chiusura centralizzata",
  "Chiusura centralizzata senza chiave",
  "Chiusura centralizzata telecomandata",
  "Climatizzatore",
  "Climatizzatore automatico",
  "Climatizzatore automatico, 2 zone",
  "Climatizzatore automatico, 3 zone",
  "Climatizzatore automatico, 4 zone",
  "Computer di bordo",
  "Controllo automatico trazione",
  "Controllo elettronico della corsia",
  "Controllo vocale",
  "Conversione biodiesel",
  "Cruise control",
  "Deflettori",
  "Divisori per bagagliaio",
  "ESP",
  "Fari al laser",
  "Fari bi-Xeno",
  "Fari di profondità antiabbagliamento",
  "Fari direzionali",
  "Fari full-LED",
  "Fari LED",
  "Fari Xenon",
  "Fendinebbia",
  "Frenata d'emergenza assistita",
  "Freno di stazionamento elettrico",
  "Funzione TV",
  "Gancio traino",
  "Guida a destra",
  "Head-up display",
  "Hill Holder",
  "Hotspot Wi-Fi",
  "Immobilizzatore elettronico",
  "Interni in pelle",
  "Isofix",
  "Kit antipanne",
  "Kit fumatori",
  "Leve al volante",
  "Limitatore di velocità",
  "Luce d'ambiente",
  "Luci diurne",
  "Luci diurne LED",
  "Marmitta catalitica",
  "MP3",
  "Pacchetto invernale",
  "Pacchetto sportivo",
  "Parabrezza riscaldato",
  "Park Distance Control",
  "Pneumatici da neve",
  "Pneumatici estivi",
  "Pneumatici quattro stagioni",
  "Pompa di calore",
  "Porta scorrevole",
  "Porta scorrevole a destra",
  "Porta scorrevole a sinistra",
  "Portapacchi",
  "Portellone posteriore elettrico",
  "Range extender",
  "Regolazione elettrica del sedile posteriore",
  "Regolazione elettrica sedili",
  "Ricarica bidirezionale",
  "Riconoscimento dei segnali stradali",
  "Riscaldamento ausiliario",
  "Ruota di riserva",
  "Ruotino",
  "Schermo multifunzione interamente digitale",
  "Sedile passeggero ribaltabile",
  "Sedile posteriore sdoppiato",
  "Sedili massaggianti",
  "Sedili posteriori riscaldabili",
  "Sedili riscaldati",
  "Sedili sportivi",
  "Sedili ventilati",
  "Sensore di luminosità",
  "Sensore di pioggia",
  "Sensori di parcheggio assistito anteriori",
  "Sensori di parcheggio assistito posteriori",
  "Servosterzo",
  "Sistema di avviso di distanza",
  "Sistema di chiamata d'emergenza",
  "Sistema di controllo pressione pneumatici",
  "Sistema di navigazione",
  "Sistema di parcheggio automatico",
  "Sistema di riconoscimento della stanchezza",
  "Sistema di visione notturna",
  "Sistema lavafari",
  "Ski bag",
  "Sospensioni pneumatiche",
  "Sospensioni sportive",
  "Sound system",
  "Specchietti laterali elettrici",
  "Specchietto retrovisore con funzione antiabbagliamento",
  "Spoiler",
  "Start/Stop Automatico",
  "Streaming musicale integrato",
  "Supporto lombare",
  "Taxi o auto a noleggio",
  "Telecamera per parcheggio assistito",
  "Tendalino",
  "Tetto panoramico",
  "Tettuccio apribile",
  "Touch screen",
  "Trazione integrale",
  "USB",
  "Veicolo elaborato",
  "Vetri oscurati",
  "Vivavoce",
  "Volante in pelle",
  "Volante multifunzione",
  "Volante riscaldato",
] as const;
